---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-service
  namespace: food2gether
  labels:
    app: session-service
spec:
  selector:
    matchLabels:
      app: session-service
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  session-service
      labels:
        app: session-service
    spec:
      containers:
      - name: session-service
        image: ghcr.io/food2gether/session-service:0.0.1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env: []
        ports:
        - containerPort: 8080
          name: session-service
      restartPolicy: Always
