name: Verify Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-native:
    uses: food2gether/workflows/.github/workflows/backend-test.yaml@main
    with:
      java_version: '17'
      profile: native
      test_results_artifact_key: test-results
  sonar:
    needs: test-native
    uses: food2gether/workflows/.github/workflows/backend-scan.yaml@main
    with:
      java_version: '17'
      test_results_artifact_key: test-results
      sonar_project_key: food2gether_session-service
      additional_args: >-
        -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
        -Dsonar.pullrequest.branch=${{ github.head_ref }}
        -Dsonar.pullrequest.base=${{ github.base_ref }}
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN }}
