name: Publish Docker Image

on:
  release:
    types: [published]

permissions:
  packages: write

jobs:
  publish:
    uses: food2gether/workflows/.github/workflows/backend-release.yaml@main
    with:
      java_version: '17'
      version: ${{ github.event.release.tag_name }}
      gh-token: ${{ secrets.GITHUB_TOKEN }}